POST https://api.line.me/v2/bot/richmenu 
Authorization: Bearer {wRPWtPVVdyRm9w4GBiB0QLUDiFul6B9HzzGon1pK2ymM+XGYcpCCLYdk4iNpm/h57toFhTgnzKBO/p78CpMXxGlu1P/330Bpq2yKqIWDL7K1EPBF+qk3ly7mH/qdyIejDISc4YXstnlLlNUZmScMVgdB04t89/1O/w1cDnyilFU=} 
Content-Type: application/json

{
  "size":{
      "width":2500,
      "height":1686
  },
  "selected": false,
  "name": "LINE Developers Info",
  "chatBarText": "Tap to open",
  "areas": [
      {
          "bounds": {
              "x": 34,
              "y": 24,
              "width": 169,
              "height": 193
          },
          "action": {
              "type": "uri",
              "uri": "https://developers.line.biz/en/news/"
          }
      },
      {
          "bounds": {
              "x": 229,
              "y": 24,
              "width": 207,
              "height": 193
          },
          "action": {
              "type": "uri",
              "uri": "https://www.line-community.me/en/"
          }
      },
      {
          "bounds": {
              "x": 461,
              "y": 24,
              "width": 173,
              "height": 193
          },
          "action": {
              "type": "uri",
              "uri": "https://engineering.linecorp.com/en/blog/"
          }
      }
  ]
}

###
POST https://api-data.line.me/v2/bot/richmenu/richmenu-65f1d7d26d92deb3027fb5398c034bbb/content
Content-Type: application/octet-stream
Content-Disposition: form-data; name="file"; filename="richmenu.png"
Authorization: Bearer {wRPWtPVVdyRm9w4GBiB0QLUDiFul6B9HzzGon1pK2ymM+XGYcpCCLYdk4iNpm/h57toFhTgnzKBO/p78CpMXxGlu1P/330Bpq2yKqIWDL7K1EPBF+qk3ly7mH/qdyIejDISc4YXstnlLlNUZmScMVgdB04t89/1O/w1cDnyilFU=} 

# ----MyBoundary
# Content-Disposition: form-data; name="file"; filename="richmenu.png"
# Content-Type: application/octet-stream



###
POST https://api.line.me/v2/bot/user/all/richmenu/richmenu-65f1d7d26d92deb3027fb5398c034bbb
Authorization: Bearer {wRPWtPVVdyRm9w4GBiB0QLUDiFul6B9HzzGon1pK2ymM+XGYcpCCLYdk4iNpm/h57toFhTgnzKBO/p78CpMXxGlu1P/330Bpq2yKqIWDL7K1EPBF+qk3ly7mH/qdyIejDISc4YXstnlLlNUZmScMVgdB04t89/1O/w1cDnyilFU=}
